apiVersion: v1
kind: ConfigMap
metadata:
  name: next-node-app-config
  namespace: next-node-app
  labels:
    app.kubernetes.io/name: next-node-app-base
    app.kubernetes.io/part-of: next-node-app-base
data:
  NODE_ENV: 'production'
  PORT: '3001'
  CORS_ORIGIN: 'http://frontend.next-node-app.svc.cluster.local:3000'
  WEBSOCKET_PATH: '/socket.io'
  NEXT_PUBLIC_API_URL: 'http://backend.next-node-app.svc.cluster.local:3001'
  NEXT_PUBLIC_WEBSOCKET_URL: 'http://backend.next-node-app.svc.cluster.local:3001'
  API_URL_INTERNAL: 'http://backend.next-node-app.svc.cluster.local:3001'
