apiVersion: v1
kind: Secret
metadata:
  name: next-node-app-secrets
  namespace: next-node-app
  labels:
    app.kubernetes.io/name: next-node-app-base
    app.kubernetes.io/part-of: next-node-app-base
type: Opaque
stringData:
  database-url: postgresql://user:password@postgres:5432/app
  redis-url: redis://:password@redis:6379
  jwt-secret: change-me
  jwt-refresh-secret: change-me-too
  session-secret: change-me-also
  nextauth-secret: change-me-nextauth
